# SPDX-FileCopyrightText: 2014 CERN.
# SPDX-License-Identifier: BSD-3-Clause

[pytest]
addopts = --isort --pydocstyle --pycodestyle --doctest-glob="*.rst" --doctest-modules --cov=flask_sitemap --cov-report=term-missing
testpaths = docs tests flask_sitemap
